#!/bin/bash
# Albany-Chiara3: Addr 192.168.1.113
# voltaire: Addr 192.168.1.25

# to setup passphraseless entry (on chiara):
# 	ssh-keygen -t dsa (enter no passwords)
#       chmod 775 ~/.ssh
#	scp ~/.ssh/id_dsa.pub suny@desktopIP:.ssh/authorized_keys

USER=$1
HOST="192.168.1.25"

if [ -z "$USER" ]; then
  echo Usage: getmycode user_folder
  exit 1
fi

echo scp mikef@$HOST:~/$USER/tekkotsu-CHIARA ~/project
scp mikef@$HOST:~/$USER/tekkotsu-CHIARA ~/project

